---
# This is my first ansible playbook
# This is a simple playbook will copy a file to remote servers
# 2 Sections of Code
# HEADER SECTION
- name: This playbook will copy a host file to all remote servers
  hosts: web
# TASK SECTION
  tasks:
    - name: To copy a file
      copy:
        src: /etc/hosts
        dest: /tmp/hosts
        owner: ansible
        group: ansible
        mode: 0755

    - name: Add cache directory
      file:
        path: /tmp/cache
        state: directory

    - name: install nginx
      yum:
        name: nginx
        state: latest

    - name: restart nginx 
      service:
        name: nginx
        state: restarted 
 
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted 
